// visualizza_apparato.cxx
// ---------------------------------------------------------------------------
// Draws the tracker apparatus (source + N_layers, geometry taken from
// config_new.h) with the tracks reconstructed on ONE event, in four
// progressively filtered variants -- same event, same 5% noise, increasingly
// strict selection at each step:
//
//   STEP 1 - every combinatorial track, NO filter on q at all (not even the
//            seed acceptance range [q_min, q_max] that FindRawTracksForEvent
//            normally applies while searching). Needs a small local raw
//            finder (FindRawTracksNoQFilter below) since the seed cut is
//            hardcoded, non-optional, in track_finder_cpu.cxx.
//   STEP 2 - STEP 1 + keep only tracks whose FITTED q falls in
//            [q_min, q_max] (config_new.h): reuses FiltraTraccePerQ with
//            q_peak=sourceY, n_sigma*sigma_q=(q_max-q_min)/2, which is
//            exactly the [q_min, q_max] window.
//   STEP 3 - STEP 2 + clone removal: reuses RimuoviCloni exactly as
//            elsewhere in the project.
//   STEP 4 - STEP 3 + the REAL calibrated selection, from an actual
//            calibration run at the same 5% noise
//            (CpuCleanedQHistogramEngine, the same pipeline as
//            analisi_sorgente.cxx). Behaviour depends on the mode:
//            * single source (USE_MULTI_SOURCE=false): one
//              RobustPeakEstimate + one FiltraTraccePerQ, nothing else --
//              exactly the original behaviour of this file.
//            * multi-source: FindMultiplePeaks looks for as many genuinely
//              significant, separated peaks as the data supports (one
//              RobustPeakEstimate call per peak, each candidate validated on
//              width, prominence and significance against the background). A
//              track is kept if its q falls in the +/-3 sigma window of ANY
//              detected peak, and the calibration histogram is also drawn
//              (fit + no-fit, one curve per peak) so the phase is visible.
//            Either way STEP 4 is ONE apparatus panel with all the selected
//            tracks together.
//
// Everything except the STEP-1 finder and the drawing itself reuses existing
// project functions (Source, Detector, RimuoviCloni, FiltraTraccePerQ,
// CalcolaTolleranzeTeoriche, CpuCleanedQHistogramEngine, RobustPeakEstimate).
//
// MULTI-SOURCE OPTION: edit the MULTI_SOURCES/USE_MULTI_SOURCE block right
// after the includes to illuminate the tracker with more than one physical
// source, at heights you choose, and see how the pipeline above (which still
// assumes a single source at sourceY for the seed window and calibration)
// reacts to that mismatch.
// ---------------------------------------------------------------------------

#include "detector.h"
#include "source.h"
#include "track_finder.h"
#include "truth.h"
#include "config_new.h"

#include <iostream>
#include <iomanip>
#include <vector>
#include <cmath>
#include <algorithm>

#include <TApplication.h>
#include <TCanvas.h>
#include <TGraph.h>
#include <TMarker.h>
#include <TLine.h>
#include <TBox.h>
#include <TH2F.h>
#include <TH1F.h>
#include <TF1.h>

// ---------------------------------------------------------------------------
// MULTI-SOURCE CONFIGURATION -- edit this block to explore what happens with
// more than one physical source, at heights you choose, illuminating the
// same tracker. The reconstruction pipeline is NOT changed: the seed
// acceptance window [q_min, q_max] and the calibration target still assume a
// single source at sourceY (config_new.h) -- that is the whole point, to see
// how the existing pipeline reacts to a physical setup it was not built for.
//
// USE_MULTI_SOURCE = false -> falls back to the original single source at
// sourceY with N_tracks tracks (config_new.h), i.e. the previous behaviour.
// USE_MULTI_SOURCE = true  -> hits are the MERGE of every source in
// MULTI_SOURCES below (same layers, same single noise pass over the merged
// pixels): each source has its own height `y` (m) and its own track count;
// the angular distribution (mean/std) stays the same for every source, only
// the height changes.
// ---------------------------------------------------------------------------
struct SourceSpec {
        float y;       // height of this source along the vertical axis (m)
        int n_tracks;  // number of tracks generated by this source
};

static const bool USE_MULTI_SOURCE = false;

static const std::vector<SourceSpec> MULTI_SOURCES = {
        {0.30f, 40},
        {0.50f, 40},
        {0.70f, 40},
};

// Generate a single event: angles -> theoretical y -> acceptance -> pixel ->
// noise -> read-back positions. Same chain as analisi_sorgente.cxx /
// studio_prestazioni.cxx.
static EventHits GenerateOneEvent(Source& sorgente, Detector& detector, float prob_rumore) {
        std::vector<float> angoli = sorgente.angles();
        std::vector<std::vector<float>> y_teoriche = sorgente.y_th(angoli);
        std::vector<std::vector<float>> y_hit_true = sorgente.Check_hits(y_teoriche);

        EventHits pixel_positions(N_layers);
        for (size_t i = 0; i < N_layers; i++) {
                std::vector<uint32_t> pixels = detector.pos2pix(y_hit_true[i]);
                sorgente.MakeNoisePhysical(prob_rumore, pixels);
                pixel_positions[i] = detector.pix2pos(pixels);
        }
        return pixel_positions;
}

// Generate a single event with hits MERGED from multiple physical sources at
// different heights (angular distribution shared across sources -- same
// mean/std as the single-source case, only the height differs). Reuses
// Source::angles(n) (the runtime-count dispatcher), Detector::pos2pix/
// pix2pos and Source::MakeNoisePhysical exactly as GenerateOneEvent does;
// only the theoretical-y formula is reimplemented here, since Source::y_th
// hardcodes the single global sourceY constant and cannot take a per-call
// height. All sources' theoretical hits (after the same 0<y<1 acceptance
// as Source::Check_hits) are collected per layer BEFORE pixelisation, so
// they land on the shared pixel grid and get a single, common noise pass --
// exactly as if they were one real event with several particle-emitting
// points.
static EventHits GenerateOneEventMultiSource(Source& sorgente, Detector& detector,
                                              const std::vector<SourceSpec>& sources,
                                              float prob_rumore) {
        std::vector<std::vector<float>> y_hit_true(N_layers);

        for (const auto& src : sources) {
                std::vector<float> angoli = sorgente.angles((size_t)src.n_tracks);
                for (size_t L = 0; L < N_layers; L++) {
                        const float x_L = d_s_l + L * dist_interlayers;
                        for (float theta : angoli) {
                                const float y = src.y + x_L * std::tan(theta);
                                if (y > 0.0f && y < 1.0f) y_hit_true[L].push_back(y); // same acceptance as Source::Check_hits
                        }
                }
        }

        EventHits pixel_positions(N_layers);
        for (size_t i = 0; i < N_layers; i++) {
                std::vector<uint32_t> pixels = detector.pos2pix(y_hit_true[i]);
                sorgente.MakeNoisePhysical(prob_rumore, pixels);
                pixel_positions[i] = detector.pix2pos(pixels);
        }
        return pixel_positions;
}

// Same physics as FindRawTracksForEvent (track_finder_cpu.cxx): anchor on
// layer 0, candidate on the last layer, nearest hit snapped on each middle
// layer to the seed line, least-squares fit, chi2 < chi2_threshold. The ONLY
// difference is that the seed acceptance check (q_seed in [q_min, q_max]) is
// removed, so every (layer0, last-layer) pair is tried -- this is the only
// way to see the fully unfiltered combinatorial background, since that check
// is hardcoded and non-optional in the mass-production finder. Deliberately
// the naive O(hits0 * hitsLast * hitsMid) version: fine for a single event,
// no need for the binary-search optimisations used in the mass-production
// path.
static std::vector<Track> FindRawTracksNoQFilter(const EventHits& hits) {
        std::vector<Track> out;
        if (hits.size() != N_layers) return out;

        const std::vector<float>& y0a = hits[0];
        const std::vector<float>& yLa = hits.back();
        if (y0a.empty() || yLa.empty()) return out;

        const float x_end = d_s_l + (N_layers - 1) * dist_interlayers;
        const float delta_x = x_end - d_s_l;

        for (size_t i = 0; i < y0a.size(); i++) {
                const float y_first = y0a[i];

                for (size_t j = 0; j < yLa.size(); j++) {
                        const float y_last = yLa[j];

                        const float m_seed = (y_last - y_first) / delta_x;
                        const float q_seed = y_last - m_seed * x_end;
                        // NOTE: no check on q_seed here -- this is the whole point of STEP 1.
                        (void)q_seed;

                        float best_y[N_layers];
                        int best_indices[N_layers];
                        best_y[0] = y_first;              best_indices[0] = (int)i;
                        best_y[N_layers - 1] = y_last;     best_indices[N_layers - 1] = (int)j;

                        bool valid = true;
                        for (size_t L = 1; L + 1 < N_layers; L++) {
                                if (hits[L].empty()) { valid = false; break; }

                                const float x_L = d_s_l + L * dist_interlayers;
                                const float y_theory = m_seed * x_L + q_seed;

                                float best_d2 = 1e18f, closest_y = 0.0f;
                                int closest_idx = -1;
                                for (size_t k = 0; k < hits[L].size(); k++) {
                                        const float dy = hits[L][k] - y_theory;
                                        const float d2 = dy * dy;
                                        if (d2 < best_d2) { best_d2 = d2; closest_y = hits[L][k]; closest_idx = (int)k; }
                                }
                                best_y[L] = closest_y;
                                best_indices[L] = closest_idx;
                        }
                        if (!valid) continue;

                        float Sx = 0.0f, Sxx = 0.0f, Sy = 0.0f, Sxy = 0.0f;
                        for (size_t L = 0; L < N_layers; L++) {
                                const float x_L = d_s_l + L * dist_interlayers;
                                Sx += x_L; Sxx += x_L * x_L;
                                Sy += best_y[L]; Sxy += x_L * best_y[L];
                        }
                        const float Nf = (float)N_layers;
                        const float Delta = Nf * Sxx - Sx * Sx;
                        if (fabsf(Delta) < 1e-6f) continue;

                        const float m_fit = (Nf * Sxy - Sx * Sy) / Delta;
                        const float q_fit = (Sxx * Sy - Sx * Sxy) / Delta;

                        float chi2 = 0.0f;
                        for (size_t L = 0; L < N_layers; L++) {
                                const float x_L = d_s_l + L * dist_interlayers;
                                const float res = best_y[L] - (m_fit * x_L + q_fit);
                                chi2 += res * res;
                        }
                        chi2 /= (sigma * sigma);
                        if (chi2 >= chi2_threshold) continue;

                        Track t;
                        t.m = m_fit; t.q = q_fit; t.chi2 = chi2;
                        for (size_t L = 0; L < N_layers; L++) t.hit_indices[L] = best_indices[L];
                        out.push_back(t);
                }
        }
        return out;
}

// Draws the apparatus (source(s) as red circles, N_layers vertical lines
// with pixel-pitch ticks, all geometry read from config_new.h) plus the
// given event's hits (green pixel boxes) and reconstructed tracks (blue
// lines extrapolated from x=source_x to the last layer). Same visual layout
// as the original single-event display. source_heights lists every physical
// source to draw a marker for (defaults to just {sourceY}, the single-source
// case); the black bracket, however, always marks the FIXED [q_min, q_max]
// seed-acceptance window from config_new.h -- the algorithm's assumption,
// which does not change even when source_heights has more than one entry.
static void DrawApparatus(TApplication& app, const char* canvas_name, const char* plot_title,
                           const EventHits& hits, const std::vector<Track>& tracks, float prob_rumore,
                           const std::vector<float>& source_heights = {sourceY}) {

        TCanvas* cv = new TCanvas(canvas_name, plot_title, 100, 100, 1200, 800);
        cv->SetGrid();
        cv->Connect("Closed()", "TApplication", &app, "Terminate()");

        TGraph* frame = new TGraph();
        frame->SetTitle(Form("%s (rumore %.0f%%, %d tracce); Asse X (m); Asse Y (m)",
                              plot_title, prob_rumore * 100.0f, (int)tracks.size()));

        const float x_last_layer = d_s_l + ((N_layers - 1) * dist_interlayers);
        const float x_max_plot = x_last_layer + 0.2f;

        // Base range: tracker height + the [q_min, q_max] reference bracket
        // + every configured source height. Without any q filter (panel 1) a
        // track's fitted q -- and therefore its y at x=0 and x=x_last_layer
        // -- can land far outside that range, so the frame is widened to
        // also contain every track's endpoints; otherwise those lines get
        // clipped/vanish outside the canvas.
        float y_min_plot = std::min(0.0f, q_min) - 0.05f;
        float y_max_plot = std::max(l_tracker, q_max) + 0.05f;
        for (float y_src : source_heights) {
                y_min_plot = std::min(y_min_plot, y_src - 0.05f);
                y_max_plot = std::max(y_max_plot, y_src + 0.05f);
        }
        for (const auto& traccia : tracks) {
                const float y_start = traccia.m * source_x + traccia.q;
                const float y_end   = traccia.m * x_last_layer + traccia.q;
                y_min_plot = std::min({y_min_plot, y_start, y_end});
                y_max_plot = std::max({y_max_plot, y_start, y_end});
        }
        const float y_margin = std::max((y_max_plot - y_min_plot) * 0.03f, 0.05f);
        y_min_plot -= y_margin;
        y_max_plot += y_margin;

        frame->SetPoint(0, -0.2f, y_min_plot);
        frame->SetPoint(1, x_max_plot, y_max_plot);
        frame->SetMarkerColor(0);
        frame->Draw("AP");

        // Source(s): filled circle (marker style 20) at (source_x, y) for
        // every configured height -- normally just {sourceY}, but several
        // when exploring a multi-source scenario (MULTI_SOURCES above).
        for (float y_src : source_heights) {
                TMarker* source_marker = new TMarker(source_x, y_src, 20);
                source_marker->SetMarkerColor(kRed);
                source_marker->SetMarkerSize(2.5);
                source_marker->Draw();
        }

        // Reference bracket at x=source_x: the FIXED [q_min, q_max] seed-
        // acceptance window from config_new.h -- the single-source position
        // the pipeline still assumes, regardless of how many red circles are
        // actually drawn above.
        const float cap_dx = 0.03f;
        TLine* q_line = new TLine(source_x, q_min, source_x, q_max);
        q_line->SetLineColor(kBlack); q_line->SetLineWidth(3); q_line->Draw();
        TLine* q_cap_top = new TLine(source_x - cap_dx, q_max, source_x + cap_dx, q_max);
        q_cap_top->SetLineColor(kBlack); q_cap_top->SetLineWidth(3); q_cap_top->Draw();
        TLine* q_cap_bot = new TLine(source_x - cap_dx, q_min, source_x + cap_dx, q_min);
        q_cap_bot->SetLineColor(kBlack); q_cap_bot->SetLineWidth(3); q_cap_bot->Draw();

        // Layers: N_layers vertical lines, equally spaced by dist_interlayers
        // starting at x = d_s_l, l_tracker tall, with a tick every l_pixel.
        const int num_pixels = (int)std::round(l_tracker / l_pixel);
        const float tick_width = 0.02f;
        for (size_t i = 0; i < N_layers; i++) {
                const float layer_x = d_s_l + (i * dist_interlayers);
                TLine* layer_line = new TLine(layer_x, 0, layer_x, l_tracker);
                layer_line->SetLineColor(kGray + 1); layer_line->SetLineWidth(2); layer_line->Draw();

                for (int p = 0; p <= num_pixels; p++) {
                        const float y_bound = p * l_pixel;
                        TLine* tick = new TLine(layer_x - tick_width / 2, y_bound, layer_x + tick_width / 2, y_bound);
                        tick->SetLineColor(kGray + 2); tick->SetLineWidth(1); tick->Draw();
                }
        }

        // Hits: pixel-sized green boxes at each fired pixel's center.
        const float hit_width = 0.06f;
        for (size_t i = 0; i < N_layers; i++) {
                const float layer_x = d_s_l + (i * dist_interlayers);
                for (float y_hit : hits[i]) {
                        const float y_bottom = y_hit - (l_pixel / 2.0f);
                        const float y_top    = y_hit + (l_pixel / 2.0f);
                        TBox* hit_pixel = new TBox(layer_x - hit_width / 2, y_bottom, layer_x + hit_width / 2, y_top);
                        hit_pixel->SetFillColor(kGreen);
                        hit_pixel->SetLineColor(kBlack);
                        hit_pixel->SetLineWidth(1);
                        hit_pixel->Draw();
                }
        }

        // Reconstructed tracks: blue lines from x=source_x to the last layer.
        for (const auto& traccia : tracks) {
                const float y_start = traccia.m * source_x + traccia.q;
                const float y_end   = traccia.m * x_last_layer + traccia.q;
                TLine* linea = new TLine(source_x, y_start, x_last_layer, y_end);
                linea->SetLineColor(kBlue);
                linea->SetLineWidth(1);
                linea->Draw();
        }

        cv->Update();
}

// 3D phase-space plot: counts vs (m, q) of the reconstructed tracks, as a
// TH2F drawn "LEGO2Z" (a 3D bar per (m,q) bin, height = counts). Same
// approach as the phase-space canvas of the original single-event display:
// bin range auto-fit to the tracks' own m/q spread (with a margin), since
// the unfiltered and calibrated populations occupy very different ranges.
static void DrawPhaseSpace3D(const char* canvas_name, const char* plot_title, const std::vector<Track>& tracks) {

        float m_min_hist = 1e9f, m_max_hist = -1e9f;
        float q_min_hist = 1e9f, q_max_hist = -1e9f;

        if (!tracks.empty()) {
                for (const auto& traccia : tracks) {
                        m_min_hist = std::min(m_min_hist, traccia.m);
                        m_max_hist = std::max(m_max_hist, traccia.m);
                        q_min_hist = std::min(q_min_hist, traccia.q);
                        q_max_hist = std::max(q_max_hist, traccia.q);
                }
        } else {
                m_min_hist = -1.0f; m_max_hist = 1.0f;
                q_min_hist = 0.0f;  q_max_hist = 1.0f;
        }

        const float m_margin = std::max((m_max_hist - m_min_hist) * 0.1f, 0.1f);
        const float q_margin = std::max((q_max_hist - q_min_hist) * 0.1f, 0.1f);

        TCanvas* cv = new TCanvas(canvas_name, plot_title, 150, 150, 900, 700);
        cv->SetGrid();

        TH2F* h_mq = new TH2F(Form("h_mq_%s", canvas_name),
                               Form("%s; Pendenza (m); Intercetta (q); Conteggi", plot_title),
                               50, m_min_hist - m_margin, m_max_hist + m_margin,
                               50, q_min_hist - q_margin, q_max_hist + q_margin);

        for (const auto& traccia : tracks) {
                h_mq->Fill(traccia.m, traccia.q);
        }

        h_mq->Draw("LEGO2Z");
        cv->Update();
}

// Iteratively finds every genuinely significant, separated peak in a q
// calibration histogram, instead of assuming there is only one. Reuses
// RobustPeakEstimate AS-IS for each individual peak: the only new logic is
// the "is this a REAL peak, and where is the next one" loop.
//
// The hard part is not finding peaks -- RobustPeakEstimate always returns
// its most prominent bump, even when what is left is just combinatorial
// background. So each candidate is validated on three independent tests:
//
//   1. WIDTH: a real source peak is roughly as wide as the detector
//      resolution predicts (sigma_teorica from the geometry). A background
//      blob is far broader. Candidates wider than max_sigma_factor *
//      sigma_teorica are rejected.
//   2. PROMINENCE: the peak must stand well ABOVE the background, not merely
//      contain many entries (a flat background contains plenty of entries
//      too). The background level is estimated robustly as the median of the
//      non-empty bins (non-empty matters: the quantised q spectrum is
//      comb-like, full of exact zeros that would drag a plain median to 0
//      and make every bump look infinitely prominent). The peak's tallest
//      bin must exceed it by at least min_prominence_ratio.
//   3. SIGNIFICANCE: the same excess must also be a >= n_sigma_signif
//      Poisson fluctuation of the background, so low-statistics noise is not
//      promoted to "source".
//
// A rejected candidate is masked out and the search CONTINUES (it does not
// stop): peaks are found in order of decreasing bin height, which is not the
// same as decreasing prominence when the background is not flat, so a real
// but slightly shorter peak can legitimately show up after a marginal one.
// Stopping at the first rejection would silently lose it. Accepted peaks are
// masked out too (+/-4 sigma window zeroed), so RobustPeakEstimate cannot
// re-find the same one. max_peaks bounds the loop. Peaks are returned sorted
// by mu. NOTE: peaks are only resolvable if the histogram binning actually
// resolves sigma_teorica -- see the N_BINS choice in main().
static std::vector<PeakEstimate> FindMultiplePeaks(const QHistogram& h_original, float sigma_teorica,
                                                     int max_peaks = 12,
                                                     float max_sigma_factor = 8.0f,
                                                     double min_prominence_ratio = 3.0,
                                                     double n_sigma_signif = 5.0) {
        std::vector<PeakEstimate> peaks;
        QHistogram residual = h_original; // deep copy: counts is a std::vector, copied by value

        // Robust background level: median of the NON-EMPTY bins of the
        // original histogram (see comment above on why zeros are skipped).
        std::vector<uint64_t> nonzero;
        nonzero.reserve(h_original.n_bins);
        for (int i = 0; i < h_original.n_bins; i++) {
                if (h_original.counts[i] > 0) nonzero.push_back(h_original.counts[i]);
        }
        double bkg_level = 0.0;
        if (!nonzero.empty()) {
                std::sort(nonzero.begin(), nonzero.end());
                bkg_level = (double)nonzero[nonzero.size() / 2];
        }

        for (int iter = 0; iter < max_peaks; iter++) {
                PeakEstimate stima = RobustPeakEstimate(residual, sigma_teorica);
                if (!stima.valid) break;

                // Tallest bin within +/-1 sigma of the candidate's centre
                // (at least one bin wide, in case sigma < bin width).
                const float half_win = std::max(stima.sigma, residual.bin_width());
                uint64_t peak_height = 0;
                for (int i = 0; i < residual.n_bins; i++) {
                        if (std::abs(residual.bin_center(i) - stima.mu) <= half_win
                            && residual.counts[i] > peak_height) {
                                peak_height = residual.counts[i];
                        }
                }

                const bool too_wide = (stima.sigma > max_sigma_factor * sigma_teorica);
                const bool prominent = (bkg_level <= 0.0)
                        ? (peak_height > 0)
                        : ((double)peak_height >= min_prominence_ratio * bkg_level);
                const bool significant = ((double)peak_height >= bkg_level + n_sigma_signif * std::sqrt(bkg_level));

                if (!too_wide && prominent && significant) peaks.push_back(stima);

                // Mask the candidate's window either way (accepted or not) and
                // keep looking: rejecting must not end the search.
                const float lo = stima.mu - 4.0f * stima.sigma;
                const float hi = stima.mu + 4.0f * stima.sigma;
                uint64_t masked = 0;
                bool any_masked = false;
                for (int i = 0; i < residual.n_bins; i++) {
                        const float center = residual.bin_center(i);
                        if (center >= lo && center <= hi) {
                                masked += residual.counts[i];
                                if (residual.counts[i] > 0) any_masked = true;
                                residual.counts[i] = 0;
                        }
                }
                if (!any_masked) break; // nothing left to remove: avoid spinning
                residual.total_tracks_found -= masked;
        }

        std::sort(peaks.begin(), peaks.end(),
                  [](const PeakEstimate& a, const PeakEstimate& b) { return a.mu < b.mu; });
        return peaks;
}

// Draws a QHistogram (as used for calibration) plus, unless draw_fit_curve
// is false, one gaussian curve per entry in `peaks` -- the same visual idiom
// as Visualizer::DrawSourceSearchAndFit in analisi_sorgente.cxx, generalised
// to several curves and reimplemented locally here (this file owns its own
// TApplication instead of going through the Visualizer class, since ROOT
// only allows one TApplication per process). Used to make the STEP-4
// calibration phase actually VISIBLE -- with multiple sources it may show
// several separated peaks instead of one clean gaussian, which is the whole
// point of looking at it directly instead of only printing numbers.
static void DrawQHistogram(const char* canvas_name, const char* plot_title,
                            const QHistogram& h, const std::vector<PeakEstimate>& peaks, bool draw_fit_curve) {

        TCanvas* cv = new TCanvas(canvas_name, plot_title, 150, 150, 900, 650);
        cv->SetGrid();

        TH1F* hq = new TH1F(Form("h_%s", canvas_name), Form("%s; q ricostruita (m); Conteggi", plot_title),
                             h.n_bins, h.q_min, h.q_max);
        for (int i = 0; i < h.n_bins; i++) hq->SetBinContent(i + 1, (double)h.counts[i]);

        hq->SetLineColor(kBlue);
        hq->Draw("HIST");

        if (draw_fit_curve) {
                // One gaussian curve per detected peak, cycling through a
                // small palette so nearby peaks stay visually distinguishable.
                static const int palette[] = {kRed, kGreen + 2, kMagenta, kOrange + 7,
                                               kCyan + 2, kViolet, kSpring + 4, kAzure + 1};
                const int n_colors = (int)(sizeof(palette) / sizeof(palette[0]));
                for (size_t p = 0; p < peaks.size(); p++) {
                        if (!peaks[p].valid) continue;
                        TF1* curva = new TF1(Form("f_%s_%zu", canvas_name, p), "gaus", h.q_min, h.q_max);
                        curva->SetParameters(hq->GetMaximum(), peaks[p].mu, std::max(peaks[p].sigma, h.bin_width()));
                        curva->SetLineColor(palette[p % n_colors]);
                        curva->SetNpx(1000);
                        curva->Draw("SAME");
                }
        }

        cv->Update();
}

int main(int argc, char* argv[]) {
        TApplication app("app", &argc, argv);

        const float mean = 0.0f;
        const float std_dev = 0.15f;
        const float prob_rumore = 0.0f; // noise fixed at 5% in every panel, as requested

        Source sorgente(mean, std_dev);
        Detector detector;

        // Single event, shared across all four panels: same hits everywhere,
        // only the selection applied on top changes step by step. Uses
        // multiple physical sources when USE_MULTI_SOURCE is true (edit the
        // MULTI_SOURCES block near the top of the file to change them).
        EventHits hits = USE_MULTI_SOURCE
                ? GenerateOneEventMultiSource(sorgente, detector, MULTI_SOURCES, prob_rumore)
                : GenerateOneEvent(sorgente, detector, prob_rumore);

        // Heights to draw a source marker for: every configured source when
        // USE_MULTI_SOURCE is on, otherwise just the single sourceY.
        std::vector<float> source_heights;
        if (USE_MULTI_SOURCE) {
                for (const auto& src : MULTI_SOURCES) source_heights.push_back(src.y);
        } else {
                source_heights.push_back(sourceY);
        }

        std::cout << "=== VISUALIZZAZIONE APPARATO (rumore fisso 5%) ===\n";
        std::cout << "Distribuzione angoli: "
                  << (USE_GAUSSIAN_ANGLES ? "GAUSSIANA N(mean, std)" : "UNIFORME [mean +/- std*sqrt(3)]")
                  << "  (mean=" << mean << ", std=" << std_dev << ")\n";
        if (USE_MULTI_SOURCE) {
                std::cout << "Sorgenti multiple attive (pipeline ancora tarata su sourceY=" << sourceY << " m):\n";
                for (const auto& src : MULTI_SOURCES) {
                        std::cout << "  y=" << src.y << " m, " << src.n_tracks << " tracce\n";
                }
        } else {
                std::cout << "Sorgente singola a y=" << sourceY << " m, " << N_tracks << " tracce\n";
        }
        std::cout << "Hit per layer: ";
        for (size_t i = 0; i < N_layers; i++) std::cout << hits[i].size() << " ";
        std::cout << "\n\n";

        // --- (1) every combinatorial track, no filter on q at all ---
        std::vector<Track> step1_nofilter = FindRawTracksNoQFilter(hits);
        std::cout << "1. nessun filtro su q                 : " << step1_nofilter.size() << " tracce\n";

        // --- (2) + keep only tracks with fitted q in [q_min, q_max]
        // (config_new.h). Reuses FiltraTraccePerQ: with q_peak=sourceY and
        // n_sigma*sigma_q = (q_max-q_min)/2, the window is exactly
        // [sourceY-(q_max-q_min)/2, sourceY+(q_max-q_min)/2] = [q_min, q_max]. ---
        std::vector<Track> step2_box = FiltraTraccePerQ(step1_nofilter, sourceY, (q_max - q_min) / 2.0f, 1.0f);
        std::cout << "2. + selezione q in [q_min,q_max]     : " << step2_box.size() << " tracce\n";

        // --- (3) + clone removal (reuses RimuoviCloni + the theoretical
        // tolerances from CalcolaTolleranzeTeoriche, exactly as elsewhere) ---
        const DefinizioneTagli tagli = CalcolaTolleranzeTeoriche();
        std::vector<Track> step3_clean = RimuoviCloni(step2_box, tagli.delta_m_cut, tagli.delta_q_cut, "apparato", /*verbose=*/false);
        std::cout << "3. + rimozione cloni                  : " << step3_clean.size() << " tracce\n";

        // --- (4) + the REAL calibrated q selection, from an actual
        // calibration run at the same 5% noise (CpuCleanedQHistogramEngine,
        // the same pipeline as analisi_sorgente.cxx). ---
        const int N_CALIB_EVENTS = 5000;
        int N_BINS = 200;
        float Q_LO = q_min - 0.05f;
        float Q_HI = q_max + 0.05f;

        // With multiple sources some of them may sit outside the config's
        // single-source window: widen the histogram range to comfortably
        // contain every configured source, otherwise their peaks would be
        // silently clipped out of the calibration histogram below.
        //
        // The binning must also be REBUILT: a fixed 200 bins over a range
        // this wide gives bins wider than the physical peak itself (with
        // q_min=0, q_max=1 the bin would be ~0.0055 m against a sigma_q of
        // ~0.00225 m), so each source peak collapses into roughly ONE bin and
        // barely rises above the combinatorial background -- peaks then fail
        // the prominence test essentially at random. Sizing the bins on the
        // theoretical sigma (as simulazione.cxx/analisi_sorgente.cxx do)
        // makes every real peak stand several times over the background.
        // Not applied in the single-source case, which keeps the original
        // fixed binning.
        if (USE_MULTI_SOURCE) {
                for (const auto& src : MULTI_SOURCES) {
                        Q_LO = std::min(Q_LO, src.y - 0.05f);
                        Q_HI = std::max(Q_HI, src.y + 0.05f);
                }
                if (tagli.sigma_q > 1e-9f) {
                        N_BINS = (int)((Q_HI - Q_LO) / (tagli.sigma_q / 4.0f));
                        N_BINS = std::max(200, std::min(N_BINS, 20000));
                }
        }

        std::cout << "4. calibrazione (" << N_CALIB_EVENTS << " eventi al 5% di rumore, "
                  << N_BINS << " bin su [" << Q_LO << ", " << Q_HI << "])...";
        std::cout.flush();

        CpuCleanedQHistogramEngine calib_engine(N_BINS, Q_LO, Q_HI);
        EventBatch batch_calib(N_CALIB_EVENTS);
        for (int e = 0; e < N_CALIB_EVENTS; e++) {
                batch_calib[e] = USE_MULTI_SOURCE
                        ? GenerateOneEventMultiSource(sorgente, detector, MULTI_SOURCES, prob_rumore)
                        : GenerateOneEvent(sorgente, detector, prob_rumore);
        }
        calib_engine.ProcessBatch(batch_calib);
        const QHistogram h_calib = calib_engine.GetHistogram();

        std::vector<Track> step4_calib;

        if (!USE_MULTI_SOURCE) {
                // SINGLE SOURCE: exactly the original behaviour -- one
                // RobustPeakEstimate, one FiltraTraccePerQ, nothing else.
                PeakEstimate stima = RobustPeakEstimate(h_calib, tagli.sigma_q);
                std::cout << " mu_q=" << stima.mu << " sigma_q=" << stima.sigma << std::endl;

                step4_calib = FiltraTraccePerQ(step3_clean, stima.mu, stima.sigma, 3.0f);
                std::cout << "4. + selezione calibrata              : " << step4_calib.size() << " tracce\n\n";
        } else {
                // MULTI-SOURCE: look for as many real peaks as the data
                // supports (see FindMultiplePeaks), then keep a track if its q
                // falls inside the +/-3 sigma window of ANY of them. NOTE: the
                // number of peaks found is NOT necessarily the number of
                // configured sources -- sources placed close together can
                // legitimately merge into a single peak.
                std::cout << std::endl;
                std::vector<PeakEstimate> picchi = FindMultiplePeaks(h_calib, tagli.sigma_q);

                std::cout << "   -> trovati " << picchi.size() << " picco/i (sorgenti configurate: "
                          << MULTI_SOURCES.size() << ")\n";
                for (size_t p = 0; p < picchi.size(); p++) {
                        std::cout << "      picco " << (p + 1) << ": mu_q=" << picchi[p].mu
                                  << "  sigma_q=" << picchi[p].sigma << "\n";
                }
                if (picchi.empty()) {
                        std::cout << "      ATTENZIONE: nessun picco significativo trovato.\n";
                }

                // Make the calibration phase actually VISIBLE (not just
                // numbers on console): draw the histogram once with every
                // found peak's curve on top and once without, like the
                // fit/no-fit pair in analisi_sorgente.cxx.
                DrawQHistogram("cv_calib_hist_fit",
                               "Istogramma di calibrazione (multi-sorgente)", h_calib, picchi, /*draw_fit_curve=*/true);
                DrawQHistogram("cv_calib_hist_nofit",
                               "Istogramma di calibrazione (multi-sorgente), senza fit", h_calib, picchi, /*draw_fit_curve=*/false);

                // Union of every peak's window: each track tested once and
                // added at most once, so tracks where two nearby windows
                // overlap are not duplicated.
                for (const auto& t : step3_clean) {
                        for (const auto& pk : picchi) {
                                if (std::abs(t.q - pk.mu) <= 3.0f * pk.sigma) {
                                        step4_calib.push_back(t);
                                        break;
                                }
                        }
                }

                // Per-peak counts, for information only (reuses
                // FiltraTraccePerQ, the same selection used project-wide).
                for (size_t p = 0; p < picchi.size(); p++) {
                        const size_t n_peak = FiltraTraccePerQ(step3_clean, picchi[p].mu, picchi[p].sigma, 3.0f).size();
                        std::cout << "      picco " << (p + 1) << ": " << n_peak << " tracce selezionate\n";
                }
                std::cout << "4. + selezione calibrata (tutti i picchi): " << step4_calib.size() << " tracce\n\n";
        }

        // --- draw the four apparatus panels ---
        DrawApparatus(app, "cv_nofilter", "1. Tutte le tracce ricostruite, nessun taglio su q", hits, step1_nofilter, prob_rumore, source_heights);
        DrawApparatus(app, "cv_qbox",     "2. Selezione dell'intercetta nel range della sorgente [q_min, q_max]", hits, step2_box, prob_rumore, source_heights);
        DrawApparatus(app, "cv_clone",    "3. Rimozione delle tracce clone", hits, step3_clean, prob_rumore, source_heights);
        DrawApparatus(app, "cv_calib",    "4. Selezione calibrata sull'intercetta (#mu_{q} #pm 3#sigma_{q})", hits, step4_calib, prob_rumore, source_heights);

        // --- 3D phase space (counts vs m vs q): nessun taglio su q, and
        // with the full calibrated selection, for direct comparison ---
        DrawPhaseSpace3D("cv_mq_nofilter", "Distribuzione tracce (m,q), nessun taglio su q", step1_nofilter);
        DrawPhaseSpace3D("cv_mq_calib",    "Distribuzione tracce (m,q), selezione calibrata", step4_calib);

        app.Run();
        return 0;
}
